version: '3.7'
services:
  memo-app:
    container_name: memo-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./

  caddy:
    image: caddy/caddy:2.7.6-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/services
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
